configfile: "config/config.yaml"

rule sleep2inputs:
    input:
        expand(
            "results/{indir}/{infile}",
            indir=config["input_namespace"]["in1"],
            infile=config["input_filename"]["in1"],
        ),
        expand(
            "results/{indir}/{infile}",
            indir=config["input_namespace"]["in2"],
            infile=config["input_filename"]["in2"],
        ),
    output:
        expand(
            "results/{outdir}/{outfile}",
            outdir=config["output_namespace"],
            outfile=config["output_filename"],
        ),
    params:
        sleeptime=config["sleeptime"],
    log:
        expand(
            "logs/{outdir}.log",
            outdir=config["output_namespace"],
        )
    benchmark:
        "benchmarks/sleep.txt"
    conda:
        "envs/conda.yaml"
    shell:
        "sleep {params.sleeptime} && echo {params.sleeptime} > {output}"
