input_namespace: null
output_namespace: utility_touch
utility_touch:
  config:
    input_namespace: null
    output_namespace: utility_touch
    params:
      filename: data.csv
  name: (Utility) touch
  snakefile:
    args:
      - jsbrittain/snakeshack
    function: github
    kwargs:
      branch: main
      path: workflows/Utility/modules/touch/workflow/Snakefile
  type: module
