configfile: "config/config.yaml"
from grapevne_helper import *

init(workflow)

rule copy:
    input:
        resource("file"),
    output:
        output(params("filename")),
    shell:
        """
        cp {input} {output}
        """

rule _test:
    input:
        src=resource("file"),
        dst=output(params("filename")),
    run:
        # Verify that the file has been copied correctly
        with open(input.src) as src, open(input.dst) as dst:
            assert src.read() == dst.read()
