configfile: "config/config.yaml"

params = config["params"]

rule copy:
    input:
        srcdir("../resources/file"),
    output:
        expand(
            "results/{outdir}/{filename}",
            outdir=config["output_namespace"],
            filename=params["filename"],
        )
    shell:
        """
        cp {input} {output}
        """
