configfile: "config/config.yaml"

module source_test:
    snakefile:
        config["source_test"]["snakefile"]
    config:
        config["source_test"]["config"]
use rule * from source_test as source_test_*

module sleep1input_test:
    snakefile:
        config["sleep1input_test"]["snakefile"]
    config:
        config["sleep1input_test"]["config"]
use rule * from sleep1input_test as sleep1input_test_*
