from snakemake.utils import min_version
min_version("6.0")

rule all:
    input:
        "results/rule6"

rule rule_1:
    output:
        "results/rule1"
    shell:
        "sleep 1 && touch results/rule1"

rule rule_6:
    input:
        "results/rule5"
    output:
        "results/rule6"
    shell:
        "sleep 5 && touch results/rule6"

module other_workflow:
    snakefile: "Snakefile.sub"

use rule * from other_workflow exclude gen_rule1 as other_*

