"""
Input namespaces: [in1, in2, in3]
Copy file from first input namespace (in1) only
"""
configfile: "config/config.yaml"
from grapevne_helper import import_grapevne
import shutil

grapevne = import_grapevne(workflow)
globals().update(vars(grapevne))

rule copy:
    input:
        input(params("filename"), "in1"),
    output:
        output(params("filename")),
    run:
        shutil.copy(input[0], output[0])

rule _test:
    input:
        src=rules.copy.input[0],
        dst=rules.copy.output[0],
    run:
        # Verify that the file has been copied correctly
        with open(input.src) as src, open(input.dst) as dst:
            assert src.read() == dst.read()
