configfile: "config/config.yaml"

from grapevne_helper import *
import os
import pathlib
import shutil

init(workflow)

rule copy:
    input:
        resource("file"),
    output:
        output(params("filename")),
    run:
        pathlib.Path(os.path.dirname(output[0])).mkdir(parents=True, exist_ok=True)
        shutil.copy(input[0], output[0])

rule _test:
    input:
        src=resource("file"),
        dst=output(params("filename")),
    run:
        # Verify that the file has been copied correctly
        with open(input.src) as src, open(input.dst) as dst:
            assert src.read() == dst.read()
