configfile: "config/config.yaml"
from grapevne_helper import import_grapevne
from pathlib import Path

grapevne = import_grapevne(workflow)
globals().update(vars(grapevne))

rule touch:
    output:
        file = output(param("filename")),
    run:
        Path(output.file).touch()

rule _test:
    input:
        rules.touch.output.file,
