configfile: "config/config.yaml"

module source_test1:
    snakefile:
        config["source_test1"]["snakefile"]
    config:
        config["source_test1"]["config"]
use rule * from source_test1 as source_test1_*

module source_test2:
    snakefile:
        config["source_test2"]["snakefile"]
    config:
        config["source_test2"]["config"]
use rule * from source_test2 as source_test2_*

module sleep2input_test:
    snakefile:
        config["sleep2input_test"]["snakefile"]
    config:
        config["sleep2input_test"]["config"]
use rule * from sleep2input_test as sleep2input_test_*
