configfile: "config/config.yaml"

module source_test:
    snakefile:
        config["source_test"]["snakefile"]
    config:
        config["source_test"]["config"]
use rule * from source_test as source_test_*

module sleep1input_test1:
    snakefile:
        config["sleep1input_test1"]["snakefile"]
    config:
        config["sleep1input_test1"]["config"]
use rule * from sleep1input_test1 as sleep1input_test1_*

module sleep1input_test2:
    snakefile:
        config["sleep1input_test2"]["snakefile"]
    config:
        config["sleep1input_test2"]["config"]
use rule * from sleep1input_test2 as sleep1input_test2_*
