name: GRAPEVNE

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  es-lint-nodemapper:
    uses: ./.github/workflows/eslint-nodemapper.yml
  jest-nodemapper:
    uses: ./.github/workflows/jest-nodemapper.yml
  es-lint-electron-app:
    uses: ./.github/workflows/eslint-electron-app.yml
  jest-electron-app:
    uses: ./.github/workflows/jest-electron-app.yml
  ruff-backend:
    uses: ./.github/workflows/ruff-backend.yml
  pytest-backend:
    uses: ./.github/workflows/pytest-backend.yml
  ruff-builder:
    uses: ./.github/workflows/ruff-builder.yml
  pytest-builder:
    uses: ./.github/workflows/pytest-builder.yml
  ruff-runner:
    uses: ./.github/workflows/ruff-runner.yml
  pytest-runner:
    uses: ./.github/workflows/pytest-runner.yml
