name: GRAPEVNE

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  nodemapper:
    uses: ./.github/workflows/nodemapper.yml
  electron-app:
    uses: ./.github/workflows/electron-app.yml
  builder:
    uses: ./.github/workflows/builder.yml
  runner:
    uses: ./.github/workflows/runner.yml
