name: nodemapper

on:
  workflow_call:

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nodemapper
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: ./run_tests.sh
